src/main/java/org/imixs/application/security/LoginController.java
/*******************************************************************************
 *  Imixs Workflow 
 *  Copyright (C) 2001, 2011 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Project: 
 *  	http://www.imixs.org
 *  	http://java.net/projects/imixs-workflow
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika - Software Developer
 *******************************************************************************/

package org.imixs.application.security;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.crypto.SecretKey;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.imixs.jwt.HMAC;
import org.imixs.jwt.JWSAlgorithm;
import org.imixs.jwt.JWTBuilder;
import org.imixs.jwt.JWTException;

/**
 * The LoginController validates a given api secret and generates an Admin Token
 * to be used to access the application and Rest API.
 * 
 * @author rsoika
 * 
 */
@Named
@RequestScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 1L;

    private static Logger logger = Logger.getLogger(LoginController.class.getName());

    private String token;
    private String secret;
    private String user;
    private String group;

    public LoginController() {
        super();
    }

    public String login() throws JWTException {

        return generateToken();
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getGroup() {
        return group;
    }

    public void setGroup(String group) {
        this.group = group;
    }

    public boolean isAuthenticated() {
        return false;
    }

    /**
     * Helper Method generating a JWT token
     * 
     * @return
     * @throws JWTException
     */
    private String generateToken() throws JWTException {
        String token = null;
        // generate a admin payload
        String payload = "{\"sub\":\"" + getUser() + "\",\"groups\":[\"" + getGroup() + "\"]}";

        logger.info("...generating new access token for " + payload);

        // try {
        // We need a signing key...
        SecretKey secretKey = HMAC.createKey(JWSAlgorithm.JDK_HS256, secret.getBytes());

        JWTBuilder builder;

        builder = new JWTBuilder().setKey(secretKey).setHeader(JWTBuilder.DEFAULT_HEADER).setPayload(payload).sign();

        token = builder.getToken();
        logger.info("token=" + builder.getToken());

        // set cookie - expire time 1 day
        setCookie("jwt", token, 3600*24);

        return "/pages/welcome.xhtml?faces-redirect=true";

    }

    /**
     * Helper method to set a cookie
     * 
     * @param name
     * @param value
     * @param expiry - max age in seconds
     */
    public void setCookie(String name, String value, int expiry) {

        FacesContext facesContext = FacesContext.getCurrentInstance();

        HttpServletRequest request = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        Cookie cookie = null;

        Cookie[] userCookies = request.getCookies();
        if (userCookies != null && userCookies.length > 0) {
            for (int i = 0; i < userCookies.length; i++) {
                if (userCookies[i].getName().equals(name)) {
                    cookie = userCookies[i];
                    break;
                }
            }
        }

        if (cookie != null) {
            cookie.setValue(value);
        } else {
            cookie = new Cookie(name, value);
            cookie.setPath(request.getContextPath());
        }

        cookie.setMaxAge(expiry);

        HttpServletResponse response = (HttpServletResponse) facesContext.getExternalContext().getResponse();
        response.addCookie(cookie);
    }

    /**
     * helper method to read a cookie
     * 
     * @param name
     * @return
     */
    public Cookie getCookie(String name) {

        FacesContext facesContext = FacesContext.getCurrentInstance();

        HttpServletRequest request = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        Cookie cookie = null;

        Cookie[] userCookies = request.getCookies();
        if (userCookies != null && userCookies.length > 0) {
            for (int i = 0; i < userCookies.length; i++) {
                if (userCookies[i].getName().equals(name)) {
                    cookie = userCookies[i];
                    return cookie;
                }
            }
        }
        return null;
    }
}

src/main/java/org/imixs/application/util/PropertyController.java
/*******************************************************************************
 *  Imixs Workflow 
 *  Copyright (C) 2001, 2011 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Project: 
 *  	http://www.imixs.org
 *  	http://java.net/projects/imixs-workflow
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika - Software Developer
 *******************************************************************************/

package org.imixs.application.util;

import java.io.Serializable;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.eclipse.microprofile.config.Config;

/**
 * This PropertyController provides access to the Microprofile config api.
 * <p>
 * The PropertyController can be used in a JSF page to access a specific property by name:
 * <p>
 * <code>
 *   #{propertyController.getProperty('my-property')}
 *   #{propertyController.getProperty('another-property','default value')}
 * </code>
 * 
 * @author rsoika
 */
@Named
@ApplicationScoped
public class PropertyController implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject Config config;

	/**
	 * Returns a property value
	 * 
	 * @param key - the property key
	 * @return property value
	 */
	public String getProperty(String key) {
		return config.getOptionalValue(key, String.class)
                .orElse("");
	}
	
	/**
     * Returns a property value
     * 
     * @param key - the property key
     * @param defaultValue - optional default value if property not defined
     * @return property value
     */
    public String getProperty(String key,String defaultValue) {
        return config.getOptionalValue(key, String.class)
                .orElse(defaultValue);
    }
}

src/main/webapp/layout/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	<h:form>
		<ul>
			<li>Imixs IoT Monitor - (imixs-workflow v.#{message.application_workflow_build})</li>
		</ul>
	</h:form>
</ui:composition>

src/main/webapp/layout/head_container.xhtml
<f:subview xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	

<div class="container" style="width: 100%;">

			<div class="sub-container">

				<div class="sub-container-box">
					<h2>Welcome</h2>
					<!--  Singed in user -->
					<h:panelGroup rendered="#{loginController.authenticated}">
						<span class="typcn typcn-key"></span>
						<h:outputText value="Login: #{loginController.userPrincipal}" />
					</h:panelGroup>
					<br /> Last Login: 10.0.0.
				</div>
				
				<div class="sub-container-box">
					<h2>Help</h2>
					<h:outputLink value="/pages/admin/profilelist.xhtml">
						<span class="typcn typcn-user"></span>
						<h:outputText value="All Users" />
					</h:outputLink>
					<br />
					<h:outputLink value="/pages/admin/spaces.xhtml">
						<span class="typcn typcn-group"></span>
						<h:outputText value="All Groups" />
					</h:outputLink>
				</div>
			</div>
		</div>




</f:subview>

src/main/webapp/layout/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough">



	<div class="container title">
		<h:outputLink value="/pages/welcome.xhtml">
			<span class="typcn typcn-home"></span>
			<h:outputText value="BPMN 2.0 Process Manager" />
		</h:outputLink>
	</div>



	<div class="container linkbox ">
		<div class="">

			<ul>
				<li><a href="https://github.com/rsoika/jakartaee-initializer"
					target="_blank">Search</a></li>
				<li><a href="https://github.com/rsoika/jakartaee-initializer"
					target="_blank">Organization</a></li>
				<li><a href="https://github.com/rsoika/jakartaee-initializer"
					target="_blank">Models</a></li>
				<li><a href="https://github.com/rsoika/jakartaee-initializer"
					target="_blank">Users</a></li>
			</ul>
		</div>
	</div>

	
	<div class="container linkbox ">
		<div class="pull-right">

			<ul>
			
				<li><a href="https://github.com/rsoika/jakartaee-initializer"
					target="_blank"><span class="typcn typcn-social-github"></span></a></li>
			</ul>
		</div>
	</div>


	<div class="container searchbox"> 
		<h:form
			onkeypress="if (event.keyCode == 13) { $('.header-search-button').click(); return false; }">

			<h:inputText style="width: 80%;" value="#{searchController.input}"
				a:placeholder="search..." />
			<h:commandLink actionListener="#{searchController.search()}"
				styleClass="header-search-button" action="/pages/search"
				title="#{global.search}">
				<span class="typcn typcn-zoom-outline"></span>
			</h:commandLink>
		</h:form>

	</div>
	


</ui:composition>

src/main/webapp/layout/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta content="text/javascript" http-equiv="Content-Script-Type" />
	<meta content="text/css" http-equiv="Content-Style-Type" />
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	<meta content="Imixs Workflow" name="keywords" />

	<title>#{message.application_title}</title>

	

	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/imixs-core.js"></script>
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/imixs-xml.js"></script>
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/layout/js/basic.js"></script>

	<!-- Load the marty component script -->
	<script type="text/javascript"
		src="#{facesContext.externalContext.requestContextPath}/marty/imixs-marty.js?build=#{app.application_build_timestamp}"></script>

	

	<!-- Fonts
	    ================================================== -->
	<link rel="stylesheet" type="text/css"
		href="#{facesContext.externalContext.requestContextPath}/layout/css/fonts/open_sans.css" />
	<link rel="stylesheet" type="text/css"
		href="#{facesContext.externalContext.requestContextPath}/layout/css/fonts/typicons.css" />

	<!-- layout -->
	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/imixs-basic.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/imixs-layout.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />

	<link
		href="#{facesContext.externalContext.requestContextPath}/marty/imixs-marty.css?build=#{app.application_build_timestamp}"
		charset="UTF-8" type="text/css" rel="stylesheet" />

	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/basic.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/chronicle.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />


	
</h:head>
<h:body>



	<f:view>
		<f:loadBundle basename="bundle.message" var="message" />




		<!-- Page Content -->
		<div class="content">

			<div id="imixs-header">
				<ui:insert name="header">
					<ui:include src="header.xhtml" />
				</ui:insert>
			</div>


			<div id="imixs-content">
			
				<ui:include src="head_container.xhtml" />
			
				<ui:insert name="content">
					<h2>Default Content</h2>
				</ui:insert>
			</div>

			<div id="imixs-footer">
				<ui:insert name="footer">
					<ui:include src="footer.xhtml" />
				</ui:insert>
			</div>

		</div>
	</f:view>




	<script type="text/javascript">
		/*<![CDATA[*/

		$(document).ready(function() {
			layoutEditor();
		});

		/* laest sich im moment nicht auslagern (script_url!) see issue #87 */
		layoutEditor = function() {
			// Layout office default editor
			tinymce
					.init({
						selector : 'textarea.imixs-editor',
						height : 300,
						plugins : [
								'advlist autolink lists link image preview',
								'searchreplace code fullscreen',
								'contextmenu paste code' ],
						toolbar : 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
						content_css : "#{facesContext.externalContext.requestContextPath}/layout/css/tinymce.css"

					});

		};

		/*]]>*/
	</script>



</h:body>

</html>

src/main/webapp/login.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">

	<ui:define name="content">

		<script type="text/javascript">
			/*<![CDATA[*/

			// set json objects with monitoring datasets 
			$(document).ready(function() {

			});

			/*]]>*/
		</script>


		<div class="container" style="width: 100%;">
			<f:view>
				<h:form>
					<h2>Login</h2>
					
					
					<dl>
						<dt>User</dt>
						<dd>
							<h:inputText value="#{loginController.user}"/>
						</dd>
					
					</dl>
					
					<dl>
					
						<dt>Group: </dt>
						<dd><h:selectOneMenu value="#{loginController.group}">
							   	<f:selectItem itemValue="org.imixs.ACCESSLEVEL.MANAGERACCESS" itemLabel="org.imixs.ACCESSLEVEL.MANAGERACCESS" />
							   	<f:selectItem itemValue="org.imixs.ACCESSLEVEL.EDITORACCESS" itemLabel="org.imixs.ACCESSLEVEL.EDITORACCESS" />
							   	<f:selectItem itemValue="org.imixs.ACCESSLEVEL.AUTHORACCESS" itemLabel="org.imixs.ACCESSLEVEL.AUTHORACCESS" />
							   	<f:selectItem itemValue="org.imixs.ACCESSLEVEL.READACCESS" itemLabel="org.imixs.ACCESSLEVEL.READACCESS" />
							</h:selectOneMenu>
						</dd>
					
					</dl>
					
					
				
					<hr />
					<p>Please enter your API secret. You will be automatically logged in with Administrative access. </p>
					
					<dl>
					
						<dt>Password:</dt>
						<dd>
							<h:inputSecret value="#{loginController.secret}"/>
						</dd>
					</dl>
						
					<br />
					<h:commandButton action="#{loginController.login()}" value="Login"></h:commandButton>
					
				</h:form>
			</f:view>
		</div>
		
		
	</ui:define>
</ui:composition>

src/main/webapp/pages/all.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">

	<ui:define name="content">
		<!-- Show task list -->
		<c:if test="#{loginController.authenticated}">
			<ui:include src="/pages/sub_view.xhtml">
				<ui:param name="view" value="#{viewHandler.getData(openTaskListController)}" />
				<ui:param name="title" value="#{message.worklist}" />
			
			</ui:include>
		</c:if>
		
	</ui:define>
</ui:composition>

src/main/webapp/pages/error_message.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">


	<!-- Display only if error messages available -->
	<h:panelGroup rendered="#{! empty facesContext.maximumSeverity}"
		styleClass="ui-widget">
		<div class="ui-state-error ui-corner-all"
			style="padding: .7em; margin-bottom: .7em;">
			<h3>
				<span class="typcn typcn-warning-outline"></span> #{message.error_title} 
			</h3> 
			<p>
				<h:outputText sxtyle="color: red" value="#{message.error_message}" />
			</p>
			<p>
				<h:messages globalOnly="true" showDetail="true" showSummary="false" />
			</p>
		</div>
	</h:panelGroup>

</ui:composition>

src/main/webapp/pages/my_statuslist.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">

	<ui:define name="content">
		<!-- Show task list -->
		<c:if test="#{loginController.authenticated}">
			<ui:include src="/pages/sub_view.xhtml">
				<ui:param name="viewController" value="#{myStatusListController}" />
				<ui:param name="title" value="#{message.my_statuslist}" />
			
			</ui:include>
		</c:if>
		
	</ui:define>
</ui:composition>

src/main/webapp/pages/my_tasklist.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">

	<ui:define name="content">
		
		<!-- Show task list -->
		<c:if test="#{loginController.authenticated}">
			<ui:include src="/pages/sub_view.xhtml">
				<ui:param name="viewController" value="#{myTaskListController}" />
				<ui:param name="title" value="#{message.my_tasklist}" />
			
			</ui:include>
		</c:if>
		
	</ui:define>
</ui:composition>

src/main/webapp/pages/search.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">

	<ui:define name="content">
	
		<ui:include src="/pages/sub_view.xhtml">
				<ui:param name="view" value="#{viewHandler.getData(searchController)}" />
				<ui:param name="title" value="Search" />
		</ui:include>
	</ui:define>
</ui:composition>

src/main/webapp/pages/sub_view.xhtml
<f:subview xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">

	<f:view>
		<h:form>
			<h2>#{title}</h2>

			<h:dataTable class="imixsdatatable" style="width:100%"
				value="#{viewHandler.getData(viewController)}" var="workitem">				
				
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{message.summary}" />
					</f:facet>
						<h:link outcome="/pages/workflow/workitem">
							<span class="typcn typcn-cog-outline"></span> <h:outputText value="#{workitem.item['$workflowSummary']}" />
							<f:param name="id" value="#{workitem.item['$uniqueid']}" />
					</h:link>
				</h:column>

				<h:column>
					<f:facet name="header">
						<h:outputText value="#{message.process}" />
					</f:facet>
					<h:outputText value="#{workitem.item['$workflowGroup']}" />
				</h:column>
				
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{message.status}" />
					</f:facet>
					<h:outputText value="#{workitem.item['$workflowstatus']}" />
				</h:column>
				
				<h:column>
					<f:facet name="header">
						<h:outputText value="Device" />
					</f:facet>
					<h:outputText value="#{workitem.item['device']}" />
				</h:column>

				<h:column>
					<f:facet name="header">
						<h:outputText value="#{message.owner}" />
					</f:facet>
					<ui:repeat var="owner" value="#{workitem.itemList['namOwner']}">
						<h:outputText value="#{owner}" />
						<br />
					</ui:repeat>
				</h:column>

				<h:column>
					<f:facet name="header">
						<h:outputText value="#{message.created}" />
					</f:facet>
					<h:outputText value="#{workitem.item['$created']}">
						<f:convertDateTime timeZone="CET" type="date" dateStyle="medium" />
					</h:outputText>
					<h:outputText value=" #{message.by} #{workitem.item['$creator']}" />
				</h:column>


				<h:column>
					<f:facet name="header">
						<h:outputText value="#{message.modified}" />
					</f:facet>
					<h:outputText value="#{workitem.item['$modified']}">
						<f:convertDateTime timeZone="CET" type="both" dateStyle="medium" />
					</h:outputText>
					<h:outputText
						value=" #{message.by} #{workitem.item['$editor']}" />
				</h:column>


				

				<h:column> 
					<h:commandLink value="#{message.delete}" onclick="return confirm('Delete this entry?');"
						action="/pages/welcome?faces-redirect=true" actionListener="#{documentController.delete(workitem.item['$uniqueid'])}"
						rendered="#{workitem.item['$isAuthor']}">
					</h:commandLink>
				</h:column>

			</h:dataTable>


			<h:commandButton actionListener="#{viewHandler.back(viewController)}"
				disabled="#{!(viewController.pageIndex>0)}"
				value="&lt;&lt; #{message.prev}">
			</h:commandButton>
			<h:commandButton actionListener="#{viewHandler.forward(viewController)}"
				disabled="#{viewController.endOfList}" 
				value="#{message.next} &gt;&gt;">
			</h:commandButton>

		</h:form>
	</f:view>


</f:subview>

src/main/webapp/resources/imixs/imixsTest.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">
<h:head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta content="text/javascript" http-equiv="Content-Script-Type" />
	<meta content="text/css" http-equiv="Content-Style-Type" />
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	

	<title>Imixs Fileupload</title>



	<i:imixsHeader />
	<link
		href="#{facesContext.externalContext.requestContextPath}/layout/css/basic.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
</h:head>
<h:body>



	<h3>Ich bin der iFrame :-) für Imixs Fileupload</h3>
	<i:imixsFileUpload id="myupload_id" />


</h:body>
</html>